spring.application.name=spring_restfulapi_dto_EMP

spring.datasource.url=jdbc:mysql://localhost:3306/restfulapi_dto_db
spring.datasource.username=root
spring.datasource.password=Vignesh@2808

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true